const CLASSNAME = {
  LAYOUT: {
    INPUT_CONTAINER: "input-container",
    BUTTON: "button",
    TITLE_PROJECT: "title-project",
    COLOR_PICKER_CONTAINER: "color-picker-container",
    ADD_COLORS: "add-colors",
    BACKGROUND_IMAGE_UPLOAD: "background-image-upload",
    UPLOAD_WRAPPER: "upload-wrapper",
    CONTAINER: "container",
    CHOOSE_TEMPLATE_SIZE: "choose-template-size",
    TITLE: "title",
    GRID: "grid",
    SIZE_DIMENSIONS: "sizeDimensions",
    SELECTED_INFO: "selectedInfo",
    FILTER: "filters",
    SAVE_FORM: "save-form",
    SAVE_TEMPLATE_CONTAINER: "save-template-container",
    TEXT_OPTIONS: "text-options",
    TEXT_INPUT_SECTION: "text-input-section",
    INPUT_GROUP: "input-group",
    TEXT_LIST: "text-list",
    TEXT_ITEMS: "text-items",
    TEXT_ITEM: "text-item",
    TEXT_INFO: "text-info",
    SELECTED: "selected",
    TEMPLATE_CONTAINER: "templates-container",
    LOADING_CONTAINER: "loading-container",
    LOADING_SPINNER: "loading-spinner",
    NO_TEMPLATE: "no-templates",
    TEMPLATE_GRID: "templates-grid",
    TEMPLATE_ITEM: "template-item",
    TEMPLATE_THUMBNAIL: "template-thumbnail",
    THUMBNAIL_PLACEHOLDER: "thumbnail-placeholder",
    TEMPLATE_INFO: "template-info",
    TEMPLATE_NAME: "template-name",
    THUMBNAIL_IMAGE: "thumbnail-image",
    PROPERTY_GROUP: "property-group",
    Z_INDEX_CONTROL: "z-index-controls",
    Z_INDEX_BUTTON: "z-index-buttons",
    SHAPE_OPTIONS: "shape-options",
    SHAPE_BUTTON: "shape-buttons",
    SHAPES: "shapes",
    TEXT_PROPERTY: "text-property",
    SELECTED_SHAPE_CONTROL: "selected-shape-controls",
    DELETE_TEXT: "delete-text",
    IMAGE_UPLOAD_SECTION: "image-upload-section",
    DRAG_DROP_AREA: "drag-drop-area",
    DRAG_OVER: "drag-over",
    DRAG_DROP_CONTENT: "drag-drop-content",
    UPLOAD_MEDIA: "upload-media",
    IMAGE_CONTROLS: "image-controls",
    SIZE_CONTROLS: "size-controls",
    FILTER_CONTROLS: "filter-controls",
    UPLOADED_IMAGES: "uploaded-images",
    IMAGES_GRID: "images-grid",
    IMAGE_THUMBNAIL: "image-thumbnail",
    SHAPE_CONTROL: "shape-controls",
    COLOR_CONTROL: "color-controls",
  },
  HEADER: {
    COLOR_TITLE: "color-title",
    SIZE_NAME: "sizeName",
  },
  BUTTON: {
    DELETE: "delete-btn",
    SIZE_OPTION: "sizeOption",
    SIZE_OPTION_SELCTED: "sizeOptionSelected",
    BUTTON: "button",
    BUTTON_DISABLED: "buttonDisabled",
    FILTER: "filter-btn",
    ACTIVE: "-active",
    FILTER_BTN_TITLE: "filter-btn-title",
    SAVE_BTN: "save-btn",
    ADD_TEXT: "add-text-btn",
    LOAD_BTN: "load-btn",
    LAYER: "layer-btn",
  },
  INPUT: {
    CHOOSE_FILE: "choose-file",
    TEMPLATE_NAME_INPUT: "template-name-input",
    FONT_SIZE: "input-font-size",
  },
  EMPTY: "",
};

export default CLASSNAME;
